### ISSUE TITLE
Get API Keys

### ISSUE THREAD

**Issue by SeymoreBiggins** [Week-Seven-Crew/Dictionario#1]
https://any-api.com/wordnik_com/wordnik_com/docs/API_Description

https://any-api.com/apitore_com/wordnetSynonymApis/docs/API_Description

https://any-api.com/apitore_com/wordnetHyponymApis/docs/API_Description

**Comment by tarrantrl** [comment]
fetch("https://wordsapiv1.p.rapidapi.com/words/hatchback/typeOf", {
	"method": "GET",
	"headers": {
		"x-rapidapi-host": "wordsapiv1.p.rapidapi.com",
		"x-rapidapi-key": "e2952ee466msh43fbf0a24fab1ddp1c8f69jsnfb29dc16feca"
	}
})

**Comment by dgib21** [comment]
Closing this one out.
